export const UNSELECT_SONG = 'UNSELECT_SONG';
export const SORTBY_NAME = 'SORTBY_NAME';
export const SORTBY_ARTIST = 'SORTBY_ARTIST';
export const SORTBY_ALBUM = 'SORTBY_ALBUM';
export const SORTBY_YEAR = 'SORTBY_YEAR';
export const SORTBY_DURATION = 'SORTBY_DURATION';
export const SORTBY_POPULARITY = 'SORTBY_POPULARITY';
export const SORTBY_BPM = 'SORTBY_BPM';
export const SORTBY_LOUDNESS = 'SORTBY_LOUDNESS';

export const FILTERBY_DURATION = 'FILTERBY_DURATION';
export const FILTERBY_POPULARITY = 'FILTERBY_POPULARITY';
export const FILTERBY_BPM = 'FILTERBY_BPM';
export const FILTERBY_LOUDNESS = 'FILTERBY_LOUDNESS';