export const TOGGLE_SELECT = 'TOGGLE_SELECT';
export const TOGGLE_SELECT_ALL = 'TOGGLE_SELECT_ALL';
export const SORT_SONGS = 'SORT_SONGS';
export const SORT_SONGS_REVERSE = 'SORT_SONGS_REVERSE';

export const FILTER_RANGE = 'FILTER_RANGE';
export const FILTERALL_OUT = 'FILTERALL_OUT';
export const FILTERALL_IN = 'FILTERALL_IN';
export const FILTER_ADD = 'FILTER_ADD';
export const FILTER_REMOVE = 'FILTER_REMOVE';